
export const LANGUAGES = [
  { code: "en",    label: "English",         flag: "🇨🇦" },
  { code: "ja",    label: "Japanese",         flag: "🇯🇵" },
  { code: "es",    label: "Spanish",          flag: "🇪🇸" },
  { code: "fr",    label: "French",           flag: "🇫🇷" },
  { code: "no",    label: "Norwegian",        flag: "🇳🇴" },
  { code: "tl",    label: "Filipino",          flag: "🇵🇭" },
  { code: "da",    label: "Danish",            flag: "🇩🇰" },
  { code: "de",    label: "German",           flag: "🇩🇪" },
  { code: "pt",    label: "Portuguese",       flag: "🇧🇷" },
  { code: "zh",    label: "Mandarin Chinese", flag: "🇨🇳" },
  { code: "ko",    label: "Korean",           flag: "🇰🇷" },
  { code: "ar",    label: "Arabic",           flag: "🇸🇦" },
  { code: "ar-LB", label: "Lebanese Arabic",  flag: "🇱🇧" },
  { code: "hi",    label: "Hindi",            flag: "🇮🇳" },
  { code: "it",    label: "Italian",          flag: "🇮🇹" },
  { code: "ru",    label: "Russian",          flag: "🇷🇺" },
  { code: "nl",    label: "Dutch",            flag: "🇳🇱" },
  { code: "tr",    label: "Turkish",          flag: "🇹🇷" },
  { code: "pl",    label: "Polish",           flag: "🇵🇱" },
];

export const COLORS = {
  bg: "#0A0A0F",
  surface: "#12121A",
  surface2: "#1A1A26",
  border: "rgba(255,255,255,0.08)",
  orange: "#E8761A",
  orangeDim: "rgba(232,118,26,0.15)",
  text: "#FFFFFF",
  textMuted: "rgba(255,255,255,0.45)",
  textDim: "rgba(255,255,255,0.18)",
  teal: "#4ECDC4",
  red: "#FF6B6B",
};
